Repository ethereumjs/ethereumjs-config, pull requests merged in 2020-10, with the labels that each got.

#37 Lerna independent mode
  .gitignore
  lerna.json
Labels: PR state: merge ready, PR state: needs review

#38 Add note about git hooks
  packages/lint/README.md
Labels: PR state: merge ready

#39 Use positional path in lint scripts
  packages/lint/cli/lint-fix.sh
  packages/lint/cli/lint.sh
Labels: PR state: needs review, type: bug, type: discussion / question

#40 v2.0.0 Releases of the libraries
  README.md
  packages/coverage/CHANGELOG.md
  packages/lint/CHANGELOG.md
  packages/typescript/CHANGELOG.md
Labels: PR state: needs review
